language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="django>=1.4.2,<1.5"
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="https://www.djangoproject.com/download/1.7c3/tarball/"

matrix:
  exclude:
  - python: "3.3"
    env: DJANGO="django>=1.4.2,<1.5"
  - python: "3.4"
    env: DJANGO="django>=1.4.2,<1.5"
install:
  - "pip install $DJANGO --use-mirrors"
script:
  - make travis
after_success:
  - coveralls
branches:
  only:
    - master