# Force the use of the new container-based infrastructure
sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_ENV="django>=1.5,<1.6 django-mptt<0.8"
  - DJANGO_ENV="django>=1.6,<1.7 django-mptt<0.8"
  - DJANGO_ENV="django>=1.7,<1.8 django-mptt<0.8"
  - DJANGO_ENV="django>=1.8,<1.9"
  - TOXENV=lint

matrix:
  exclude:
  - python: "3.3"
    env: TOXENV=lint
  - python: "3.4"
    env: TOXENV=lint
  - python: "3.5"
    env: DJANGO_ENV="django>=1.5,<1.6"
  - python: "3.5"
    env: DJANGO_ENV="django>=1.6,<1.7"
  - python: "3.5"
    env: DJANGO_ENV="django>=1.7,<1.8"

install:
  - "pip install $DJANGO_ENV"
script:
  - make travis
after_success:
  - coveralls
branches:
  only:
    - master
