dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.7
    - mysql-client-core-5.7
    - mysql-client-5.7

language: python

services:
  - postgresql
  - mysql

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_ENV="django>=1.8,<1.9" DB=sqlite
  - DJANGO_ENV="django>=1.8,<1.9" DB=postgres
  - DJANGO_ENV="django>=1.8,<1.9" DB=mysql
  - DJANGO_ENV="django>=1.9,<1.10" DB=sqlite
  - DJANGO_ENV="django>=1.9,<1.10" DB=postgres
  - DJANGO_ENV="django>=1.9,<1.10" DB=mysql
  - DJANGO_ENV="django>=1.10,<1.11" DB=sqlite
  - DJANGO_ENV="django>=1.10,<1.11" DB=postgres
  - DJANGO_ENV="django>=1.10,<1.11" DB=mysql

matrix:
  exclude:
  - python: "3.3"
    env: DJANGO_ENV="django>=1.9,<1.10" DB=sqlite
  - python: "3.3"
    env: DJANGO_ENV="django>=1.9,<1.10" DB=postgres
  - python: "3.3"
    env: DJANGO_ENV="django>=1.9,<1.10" DB=mysql
  - python: "3.3"
    env: DJANGO_ENV="django>=1.10,<1.11" DB=sqlite
  - python: "3.3"
    env: DJANGO_ENV="django>=1.10,<1.11" DB=postgres
  - python: "3.3"
    env: DJANGO_ENV="django>=1.10,<1.11" DB=mysql

install:
  - if [[ $DB == "mysql" ]]; then pip install -q mysqlclient; fi
  - if [[ $DB == "postgres" ]]; then pip install -q psycopg2; fi
  - pip install $DJANGO_ENV
before_script:
  - mysql -u root -e 'create database machina_test;'
  - psql -c 'create database machina_test;' -U postgres
script:
  - make travis
after_success:
  - codecov
branches:
  only:
    - master
